version: '3'
networks:
  sebnet:
    driver: overlay

services:

  gogs:
    image: gogs/gogs:latest
    networks:
      - sebnet
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /home/seboss666/docker/gogs/:/var/gogs/
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  dnsupdate:
    image: registry.seboss666.ovh/ovhdnsupdate:latest
    networks:
      - sebnet
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager