version: '3'
services:

  pgdb:
    image: postgresql:9.4
    networks:
      - sebnet
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - /home/seboss666/docker/postgresql/data/:/var/lib/postgresql/data/
    deploy: 
      mode: global
      restart_policy:
        condition: always

  gogs:
    image: gogs/gogs:latest
    network:
      - sebnet
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /home/seboss666/docker/gogs/:/var/gogs/
    deploy:
      mode: global
      restart_policy:
        condition: always
