version: '3'
networks:
  sebnet:
    driver: overlay

services:

  pgdb:
    image: postgres:9.4
    networks:
      - sebnet
    ports:
      - "5432:5432"
    volumes:
      - /home/seboss666/docker/postgresql/data/:/var/lib/postgresql/data/
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  gogs:
    image: gogs/gogs:latest
    networks:
      - sebnet
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /home/seboss666/docker/gogs/:/var/gogs/
    deploy:
      replicas: 1
      restart_policy:
        condition: any


  # DNSupdate:
  #   image: <to-define>
  #   volumes:
  #   - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == manager