version: "3.2"
networks:
  sebnet:
    driver: overlay

volumes:
  gogs_data:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.200,rw,nfsvers=3,nolock,soft,exec"
      device: ":/volume1/Docker/gogs"

services:

  gogs:
    image: gogs/gogs:0.11.91
    environment:
      - "PUID:1001"
      - "PGID:1001"
    networks:
      - sebnet
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - type: volume
        source: gogs_data
        target: /data
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  dnsupdate:
    image: registry.seboss666.ovh/ovhdnsupdate:latest
    environment:
      - "CRON_SCHEDULE=* * * * *"
    networks:
      - sebnet
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager